//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Activity {
    
    private ActivityComputer computerField;
    
    private ActivityGeneralInformation generalInformationField;
    
    private ActivityEntry[] entriesField;
    
    private ActivityMarker[] markersField;
    
    private string fileDateField;
    
    private int revisionField;
    
    private bool revisionFieldSpecified;
    
    /// <remarks/>
    public ActivityComputer Computer {
        get {
            return this.computerField;
        }
        set {
            this.computerField = value;
        }
    }
    
    /// <remarks/>
    public ActivityGeneralInformation GeneralInformation {
        get {
            return this.generalInformationField;
        }
        set {
            this.generalInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Entry", IsNullable=false)]
    public ActivityEntry[] Entries {
        get {
            return this.entriesField;
        }
        set {
            this.entriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Marker", IsNullable=false)]
    public ActivityMarker[] Markers {
        get {
            return this.markersField;
        }
        set {
            this.markersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fileDate {
        get {
            return this.fileDateField;
        }
        set {
            this.fileDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int revision {
        get {
            return this.revisionField;
        }
        set {
            this.revisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool revisionSpecified {
        get {
            return this.revisionFieldSpecified;
        }
        set {
            this.revisionFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ActivityComputer {
    
    private string unitField;
    
    private string serialField;
    
    private string activityTypeField;
    
    private string dateCodeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string serial {
        get {
            return this.serialField;
        }
        set {
            this.serialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string activityType {
        get {
            return this.activityTypeField;
        }
        set {
            this.activityTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dateCode {
        get {
            return this.dateCodeField;
        }
        set {
            this.dateCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ActivityGeneralInformation {
    
    private ActivityGeneralInformationUser userField;
    
    private string sportField;
    
    private int ageField;
    
    private string gUIDField;
    
    private string activityStatusField;
    
    private decimal altitudeDifferencesDownhillField;
    
    private decimal altitudeDifferencesUphillField;
    
    private decimal averageAltitudeField;
    
    private decimal averageCadenceField;
    
    private decimal averageHeartrateField;
    
    private decimal averageInclineDownhillField;
    
    private decimal averageInclineUphillField;
    
    private decimal averagePowerField;
    
    private decimal averagePowerWattPerKGField;
    
    private decimal averageRiseRateField;
    
    private decimal averageRiseRateUphillField;
    
    private decimal averageRiseRateDownhillField;
    
    private decimal averageSpeedField;
    
    private decimal averageSpeedDownhillField;
    
    private decimal averageSpeedUphillField;
    
    private decimal averageTemperatureField;
    
    private string bikeField;
    
    private decimal bikeWeightField;
    
    private decimal bodyHeightField;
    
    private decimal bodyWeightField;
    
    private decimal caloriesField;
    
    private string descriptionField;
    
    private decimal distanceField;
    
    private decimal distanceDownhillField;
    
    private decimal distanceUphillField;
    
    private decimal exerciseTimeField;
    
    private string externalLinkField;
    
    private decimal hrMaxField;
    
    private decimal intensityZone1StartField;
    
    private decimal intensityZone2StartField;
    
    private decimal intensityZone3StartField;
    
    private decimal intensityZone4StartField;
    
    private decimal intensityZone4EndField;
    
    private decimal latitudeEndField;
    
    private decimal latitudeStartField;
    
    private string linkedTrackGUIDField;
    
    private decimal longitudeEndField;
    
    private decimal longitudeStartField;
    
    private decimal manualTemperatureField;
    
    private decimal maximumAltitudeField;
    
    private decimal maximumCadenceField;
    
    private decimal maximumHeartrateField;
    
    private decimal maximumInclineField;
    
    private decimal maximumInclineDownhillField;
    
    private decimal maximumInclineUphillField;
    
    private decimal maximumPowerField;
    
    private decimal maximumRiseRateField;
    
    private decimal maximumSpeedField;
    
    private decimal maximumTemperatureField;
    
    private string measurementField;
    
    private decimal minimumAltitudeField;
    
    private decimal minimumCadenceField;
    
    private decimal minimumHeartrateField;
    
    private decimal minimumInclineField;
    
    private decimal minimumPowerField;
    
    private decimal minimumRiseRateField;
    
    private decimal minimumSpeedField;
    
    private decimal minimumTemperatureField;
    
    private string nameField;
    
    private decimal pauseTimeField;
    
    private decimal powerZone1StartField;
    
    private decimal powerZone2StartField;
    
    private decimal powerZone3StartField;
    
    private decimal powerZone4StartField;
    
    private decimal powerZone5StartField;
    
    private decimal powerZone6StartField;
    
    private decimal powerZone7EndField;
    
    private decimal powerZone7StartField;
    
    private decimal ratingField;
    
    private decimal feelingField;
    
    private decimal trainingTimeDownhillField;
    
    private decimal trainingTimeUphillField;
    
    private decimal samplingRateField;
    
    private decimal shoulderWidthField;
    
    private string startDateField;
    
    private string statisticField;
    
    private decimal timeInIntensityZone1Field;
    
    private decimal timeInIntensityZone2Field;
    
    private decimal timeInIntensityZone3Field;
    
    private decimal timeInIntensityZone4Field;
    
    private decimal timeOverIntensityZoneField;
    
    private decimal timeUnderIntensityZoneField;
    
    private decimal trackProfileField;
    
    private decimal trainingTimeField;
    
    private string trainingTypeField;
    
    private decimal weatherField;
    
    private decimal wheelSizeField;
    
    private decimal windField;
    
    private decimal workInKJField;
    
    private decimal best5KTimeField;
    
    private decimal best5KEntryField;
    
    private decimal powerNPField;
    
    private decimal powerTSSField;
    
    private decimal powerFTPField;
    
    private decimal pedalingTimeField;
    
    private decimal pedalingIndexField;
    
    private decimal averageBalanceRightField;
    
    private decimal averageBalanceLeftField;
    
    private decimal powerIFField;
    
    private decimal torqueEffectLeftField;
    
    private decimal torqueEffectRightField;
    
    private decimal pedalSmoothLeftField;
    
    private decimal pedalSmoothRightField;
    
    private decimal averageCadenceCalcField;
    
    private decimal averagePowerCalcField;
    
    private string simpleHeaderValuesCalculationField;
    
    private string sharingInfoField;
    
    private string participantField;
    
    /// <remarks/>
    public ActivityGeneralInformationUser user {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    public string sport {
        get {
            return this.sportField;
        }
        set {
            this.sportField = value;
        }
    }
    
    /// <remarks/>
    public int age {
        get {
            return this.ageField;
        }
        set {
            this.ageField = value;
        }
    }
    
    /// <remarks/>
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
    
    /// <remarks/>
    public string activityStatus {
        get {
            return this.activityStatusField;
        }
        set {
            this.activityStatusField = value;
        }
    }
    
    /// <remarks/>
    public decimal altitudeDifferencesDownhill {
        get {
            return this.altitudeDifferencesDownhillField;
        }
        set {
            this.altitudeDifferencesDownhillField = value;
        }
    }
    
    /// <remarks/>
    public decimal altitudeDifferencesUphill {
        get {
            return this.altitudeDifferencesUphillField;
        }
        set {
            this.altitudeDifferencesUphillField = value;
        }
    }
    
    /// <remarks/>
    public decimal averageAltitude {
        get {
            return this.averageAltitudeField;
        }
        set {
            this.averageAltitudeField = value;
        }
    }
    
    /// <remarks/>
    public decimal averageCadence {
        get {
            return this.averageCadenceField;
        }
        set {
            this.averageCadenceField = value;
        }
    }
    
    /// <remarks/>
    public decimal averageHeartrate {
        get {
            return this.averageHeartrateField;
        }
        set {
            this.averageHeartrateField = value;
        }
    }
    
    /// <remarks/>
    public decimal averageInclineDownhill {
        get {
            return this.averageInclineDownhillField;
        }
        set {
            this.averageInclineDownhillField = value;
        }
    }
    
    /// <remarks/>
    public decimal averageInclineUphill {
        get {
            return this.averageInclineUphillField;
        }
        set {
            this.averageInclineUphillField = value;
        }
    }
    
    /// <remarks/>
    public decimal averagePower {
        get {
            return this.averagePowerField;
        }
        set {
            this.averagePowerField = value;
        }
    }
    
    /// <remarks/>
    public decimal averagePowerWattPerKG {
        get {
            return this.averagePowerWattPerKGField;
        }
        set {
            this.averagePowerWattPerKGField = value;
        }
    }
    
    /// <remarks/>
    public decimal averageRiseRate {
        get {
            return this.averageRiseRateField;
        }
        set {
            this.averageRiseRateField = value;
        }
    }
    
    /// <remarks/>
    public decimal averageRiseRateUphill {
        get {
            return this.averageRiseRateUphillField;
        }
        set {
            this.averageRiseRateUphillField = value;
        }
    }
    
    /// <remarks/>
    public decimal averageRiseRateDownhill {
        get {
            return this.averageRiseRateDownhillField;
        }
        set {
            this.averageRiseRateDownhillField = value;
        }
    }
    
    /// <remarks/>
    public decimal averageSpeed {
        get {
            return this.averageSpeedField;
        }
        set {
            this.averageSpeedField = value;
        }
    }
    
    /// <remarks/>
    public decimal averageSpeedDownhill {
        get {
            return this.averageSpeedDownhillField;
        }
        set {
            this.averageSpeedDownhillField = value;
        }
    }
    
    /// <remarks/>
    public decimal averageSpeedUphill {
        get {
            return this.averageSpeedUphillField;
        }
        set {
            this.averageSpeedUphillField = value;
        }
    }
    
    /// <remarks/>
    public decimal averageTemperature {
        get {
            return this.averageTemperatureField;
        }
        set {
            this.averageTemperatureField = value;
        }
    }
    
    /// <remarks/>
    public string bike {
        get {
            return this.bikeField;
        }
        set {
            this.bikeField = value;
        }
    }
    
    /// <remarks/>
    public decimal bikeWeight {
        get {
            return this.bikeWeightField;
        }
        set {
            this.bikeWeightField = value;
        }
    }
    
    /// <remarks/>
    public decimal bodyHeight {
        get {
            return this.bodyHeightField;
        }
        set {
            this.bodyHeightField = value;
        }
    }
    
    /// <remarks/>
    public decimal bodyWeight {
        get {
            return this.bodyWeightField;
        }
        set {
            this.bodyWeightField = value;
        }
    }
    
    /// <remarks/>
    public decimal calories {
        get {
            return this.caloriesField;
        }
        set {
            this.caloriesField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public decimal distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    public decimal distanceDownhill {
        get {
            return this.distanceDownhillField;
        }
        set {
            this.distanceDownhillField = value;
        }
    }
    
    /// <remarks/>
    public decimal distanceUphill {
        get {
            return this.distanceUphillField;
        }
        set {
            this.distanceUphillField = value;
        }
    }
    
    /// <remarks/>
    public decimal exerciseTime {
        get {
            return this.exerciseTimeField;
        }
        set {
            this.exerciseTimeField = value;
        }
    }
    
    /// <remarks/>
    public string externalLink {
        get {
            return this.externalLinkField;
        }
        set {
            this.externalLinkField = value;
        }
    }
    
    /// <remarks/>
    public decimal hrMax {
        get {
            return this.hrMaxField;
        }
        set {
            this.hrMaxField = value;
        }
    }
    
    /// <remarks/>
    public decimal intensityZone1Start {
        get {
            return this.intensityZone1StartField;
        }
        set {
            this.intensityZone1StartField = value;
        }
    }
    
    /// <remarks/>
    public decimal intensityZone2Start {
        get {
            return this.intensityZone2StartField;
        }
        set {
            this.intensityZone2StartField = value;
        }
    }
    
    /// <remarks/>
    public decimal intensityZone3Start {
        get {
            return this.intensityZone3StartField;
        }
        set {
            this.intensityZone3StartField = value;
        }
    }
    
    /// <remarks/>
    public decimal intensityZone4Start {
        get {
            return this.intensityZone4StartField;
        }
        set {
            this.intensityZone4StartField = value;
        }
    }
    
    /// <remarks/>
    public decimal intensityZone4End {
        get {
            return this.intensityZone4EndField;
        }
        set {
            this.intensityZone4EndField = value;
        }
    }
    
    /// <remarks/>
    public decimal latitudeEnd {
        get {
            return this.latitudeEndField;
        }
        set {
            this.latitudeEndField = value;
        }
    }
    
    /// <remarks/>
    public decimal latitudeStart {
        get {
            return this.latitudeStartField;
        }
        set {
            this.latitudeStartField = value;
        }
    }
    
    /// <remarks/>
    public string linkedTrackGUID {
        get {
            return this.linkedTrackGUIDField;
        }
        set {
            this.linkedTrackGUIDField = value;
        }
    }
    
    /// <remarks/>
    public decimal longitudeEnd {
        get {
            return this.longitudeEndField;
        }
        set {
            this.longitudeEndField = value;
        }
    }
    
    /// <remarks/>
    public decimal longitudeStart {
        get {
            return this.longitudeStartField;
        }
        set {
            this.longitudeStartField = value;
        }
    }
    
    /// <remarks/>
    public decimal manualTemperature {
        get {
            return this.manualTemperatureField;
        }
        set {
            this.manualTemperatureField = value;
        }
    }
    
    /// <remarks/>
    public decimal maximumAltitude {
        get {
            return this.maximumAltitudeField;
        }
        set {
            this.maximumAltitudeField = value;
        }
    }
    
    /// <remarks/>
    public decimal maximumCadence {
        get {
            return this.maximumCadenceField;
        }
        set {
            this.maximumCadenceField = value;
        }
    }
    
    /// <remarks/>
    public decimal maximumHeartrate {
        get {
            return this.maximumHeartrateField;
        }
        set {
            this.maximumHeartrateField = value;
        }
    }
    
    /// <remarks/>
    public decimal maximumIncline {
        get {
            return this.maximumInclineField;
        }
        set {
            this.maximumInclineField = value;
        }
    }
    
    /// <remarks/>
    public decimal maximumInclineDownhill {
        get {
            return this.maximumInclineDownhillField;
        }
        set {
            this.maximumInclineDownhillField = value;
        }
    }
    
    /// <remarks/>
    public decimal maximumInclineUphill {
        get {
            return this.maximumInclineUphillField;
        }
        set {
            this.maximumInclineUphillField = value;
        }
    }
    
    /// <remarks/>
    public decimal maximumPower {
        get {
            return this.maximumPowerField;
        }
        set {
            this.maximumPowerField = value;
        }
    }
    
    /// <remarks/>
    public decimal maximumRiseRate {
        get {
            return this.maximumRiseRateField;
        }
        set {
            this.maximumRiseRateField = value;
        }
    }
    
    /// <remarks/>
    public decimal maximumSpeed {
        get {
            return this.maximumSpeedField;
        }
        set {
            this.maximumSpeedField = value;
        }
    }
    
    /// <remarks/>
    public decimal maximumTemperature {
        get {
            return this.maximumTemperatureField;
        }
        set {
            this.maximumTemperatureField = value;
        }
    }
    
    /// <remarks/>
    public string measurement {
        get {
            return this.measurementField;
        }
        set {
            this.measurementField = value;
        }
    }
    
    /// <remarks/>
    public decimal minimumAltitude {
        get {
            return this.minimumAltitudeField;
        }
        set {
            this.minimumAltitudeField = value;
        }
    }
    
    /// <remarks/>
    public decimal minimumCadence {
        get {
            return this.minimumCadenceField;
        }
        set {
            this.minimumCadenceField = value;
        }
    }
    
    /// <remarks/>
    public decimal minimumHeartrate {
        get {
            return this.minimumHeartrateField;
        }
        set {
            this.minimumHeartrateField = value;
        }
    }
    
    /// <remarks/>
    public decimal minimumIncline {
        get {
            return this.minimumInclineField;
        }
        set {
            this.minimumInclineField = value;
        }
    }
    
    /// <remarks/>
    public decimal minimumPower {
        get {
            return this.minimumPowerField;
        }
        set {
            this.minimumPowerField = value;
        }
    }
    
    /// <remarks/>
    public decimal minimumRiseRate {
        get {
            return this.minimumRiseRateField;
        }
        set {
            this.minimumRiseRateField = value;
        }
    }
    
    /// <remarks/>
    public decimal minimumSpeed {
        get {
            return this.minimumSpeedField;
        }
        set {
            this.minimumSpeedField = value;
        }
    }
    
    /// <remarks/>
    public decimal minimumTemperature {
        get {
            return this.minimumTemperatureField;
        }
        set {
            this.minimumTemperatureField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public decimal pauseTime {
        get {
            return this.pauseTimeField;
        }
        set {
            this.pauseTimeField = value;
        }
    }
    
    /// <remarks/>
    public decimal powerZone1Start {
        get {
            return this.powerZone1StartField;
        }
        set {
            this.powerZone1StartField = value;
        }
    }
    
    /// <remarks/>
    public decimal powerZone2Start {
        get {
            return this.powerZone2StartField;
        }
        set {
            this.powerZone2StartField = value;
        }
    }
    
    /// <remarks/>
    public decimal powerZone3Start {
        get {
            return this.powerZone3StartField;
        }
        set {
            this.powerZone3StartField = value;
        }
    }
    
    /// <remarks/>
    public decimal powerZone4Start {
        get {
            return this.powerZone4StartField;
        }
        set {
            this.powerZone4StartField = value;
        }
    }
    
    /// <remarks/>
    public decimal powerZone5Start {
        get {
            return this.powerZone5StartField;
        }
        set {
            this.powerZone5StartField = value;
        }
    }
    
    /// <remarks/>
    public decimal powerZone6Start {
        get {
            return this.powerZone6StartField;
        }
        set {
            this.powerZone6StartField = value;
        }
    }
    
    /// <remarks/>
    public decimal powerZone7End {
        get {
            return this.powerZone7EndField;
        }
        set {
            this.powerZone7EndField = value;
        }
    }
    
    /// <remarks/>
    public decimal powerZone7Start {
        get {
            return this.powerZone7StartField;
        }
        set {
            this.powerZone7StartField = value;
        }
    }
    
    /// <remarks/>
    public decimal rating {
        get {
            return this.ratingField;
        }
        set {
            this.ratingField = value;
        }
    }
    
    /// <remarks/>
    public decimal feeling {
        get {
            return this.feelingField;
        }
        set {
            this.feelingField = value;
        }
    }
    
    /// <remarks/>
    public decimal trainingTimeDownhill {
        get {
            return this.trainingTimeDownhillField;
        }
        set {
            this.trainingTimeDownhillField = value;
        }
    }
    
    /// <remarks/>
    public decimal trainingTimeUphill {
        get {
            return this.trainingTimeUphillField;
        }
        set {
            this.trainingTimeUphillField = value;
        }
    }
    
    /// <remarks/>
    public decimal samplingRate {
        get {
            return this.samplingRateField;
        }
        set {
            this.samplingRateField = value;
        }
    }
    
    /// <remarks/>
    public decimal shoulderWidth {
        get {
            return this.shoulderWidthField;
        }
        set {
            this.shoulderWidthField = value;
        }
    }
    
    /// <remarks/>
    public string startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    public string statistic {
        get {
            return this.statisticField;
        }
        set {
            this.statisticField = value;
        }
    }
    
    /// <remarks/>
    public decimal timeInIntensityZone1 {
        get {
            return this.timeInIntensityZone1Field;
        }
        set {
            this.timeInIntensityZone1Field = value;
        }
    }
    
    /// <remarks/>
    public decimal timeInIntensityZone2 {
        get {
            return this.timeInIntensityZone2Field;
        }
        set {
            this.timeInIntensityZone2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal timeInIntensityZone3 {
        get {
            return this.timeInIntensityZone3Field;
        }
        set {
            this.timeInIntensityZone3Field = value;
        }
    }
    
    /// <remarks/>
    public decimal timeInIntensityZone4 {
        get {
            return this.timeInIntensityZone4Field;
        }
        set {
            this.timeInIntensityZone4Field = value;
        }
    }
    
    /// <remarks/>
    public decimal timeOverIntensityZone {
        get {
            return this.timeOverIntensityZoneField;
        }
        set {
            this.timeOverIntensityZoneField = value;
        }
    }
    
    /// <remarks/>
    public decimal timeUnderIntensityZone {
        get {
            return this.timeUnderIntensityZoneField;
        }
        set {
            this.timeUnderIntensityZoneField = value;
        }
    }
    
    /// <remarks/>
    public decimal trackProfile {
        get {
            return this.trackProfileField;
        }
        set {
            this.trackProfileField = value;
        }
    }
    
    /// <remarks/>
    public decimal trainingTime {
        get {
            return this.trainingTimeField;
        }
        set {
            this.trainingTimeField = value;
        }
    }
    
    /// <remarks/>
    public string trainingType {
        get {
            return this.trainingTypeField;
        }
        set {
            this.trainingTypeField = value;
        }
    }
    
    /// <remarks/>
    public decimal weather {
        get {
            return this.weatherField;
        }
        set {
            this.weatherField = value;
        }
    }
    
    /// <remarks/>
    public decimal wheelSize {
        get {
            return this.wheelSizeField;
        }
        set {
            this.wheelSizeField = value;
        }
    }
    
    /// <remarks/>
    public decimal wind {
        get {
            return this.windField;
        }
        set {
            this.windField = value;
        }
    }
    
    /// <remarks/>
    public decimal workInKJ {
        get {
            return this.workInKJField;
        }
        set {
            this.workInKJField = value;
        }
    }
    
    /// <remarks/>
    public decimal best5KTime {
        get {
            return this.best5KTimeField;
        }
        set {
            this.best5KTimeField = value;
        }
    }
    
    /// <remarks/>
    public decimal best5KEntry {
        get {
            return this.best5KEntryField;
        }
        set {
            this.best5KEntryField = value;
        }
    }
    
    /// <remarks/>
    public decimal powerNP {
        get {
            return this.powerNPField;
        }
        set {
            this.powerNPField = value;
        }
    }
    
    /// <remarks/>
    public decimal powerTSS {
        get {
            return this.powerTSSField;
        }
        set {
            this.powerTSSField = value;
        }
    }
    
    /// <remarks/>
    public decimal powerFTP {
        get {
            return this.powerFTPField;
        }
        set {
            this.powerFTPField = value;
        }
    }
    
    /// <remarks/>
    public decimal pedalingTime {
        get {
            return this.pedalingTimeField;
        }
        set {
            this.pedalingTimeField = value;
        }
    }
    
    /// <remarks/>
    public decimal pedalingIndex {
        get {
            return this.pedalingIndexField;
        }
        set {
            this.pedalingIndexField = value;
        }
    }
    
    /// <remarks/>
    public decimal averageBalanceRight {
        get {
            return this.averageBalanceRightField;
        }
        set {
            this.averageBalanceRightField = value;
        }
    }
    
    /// <remarks/>
    public decimal averageBalanceLeft {
        get {
            return this.averageBalanceLeftField;
        }
        set {
            this.averageBalanceLeftField = value;
        }
    }
    
    /// <remarks/>
    public decimal powerIF {
        get {
            return this.powerIFField;
        }
        set {
            this.powerIFField = value;
        }
    }
    
    /// <remarks/>
    public decimal torqueEffectLeft {
        get {
            return this.torqueEffectLeftField;
        }
        set {
            this.torqueEffectLeftField = value;
        }
    }
    
    /// <remarks/>
    public decimal torqueEffectRight {
        get {
            return this.torqueEffectRightField;
        }
        set {
            this.torqueEffectRightField = value;
        }
    }
    
    /// <remarks/>
    public decimal pedalSmoothLeft {
        get {
            return this.pedalSmoothLeftField;
        }
        set {
            this.pedalSmoothLeftField = value;
        }
    }
    
    /// <remarks/>
    public decimal pedalSmoothRight {
        get {
            return this.pedalSmoothRightField;
        }
        set {
            this.pedalSmoothRightField = value;
        }
    }
    
    /// <remarks/>
    public decimal averageCadenceCalc {
        get {
            return this.averageCadenceCalcField;
        }
        set {
            this.averageCadenceCalcField = value;
        }
    }
    
    /// <remarks/>
    public decimal averagePowerCalc {
        get {
            return this.averagePowerCalcField;
        }
        set {
            this.averagePowerCalcField = value;
        }
    }
    
    /// <remarks/>
    public string simpleHeaderValuesCalculation {
        get {
            return this.simpleHeaderValuesCalculationField;
        }
        set {
            this.simpleHeaderValuesCalculationField = value;
        }
    }
    
    /// <remarks/>
    public string sharingInfo {
        get {
            return this.sharingInfoField;
        }
        set {
            this.sharingInfoField = value;
        }
    }
    
    /// <remarks/>
    public string Participant {
        get {
            return this.participantField;
        }
        set {
            this.participantField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ActivityGeneralInformationUser {
    
    private int colorField;
    
    private bool colorFieldSpecified;
    
    private string genderField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool colorSpecified {
        get {
            return this.colorFieldSpecified;
        }
        set {
            this.colorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ActivityEntry {
    
    private decimal altitudeField;
    
    private bool altitudeFieldSpecified;
    
    private decimal altitudeDifferencesDownhillField;
    
    private bool altitudeDifferencesDownhillFieldSpecified;
    
    private decimal altitudeDifferencesUphillField;
    
    private bool altitudeDifferencesUphillFieldSpecified;
    
    private decimal cadenceField;
    
    private bool cadenceFieldSpecified;
    
    private decimal caloriesField;
    
    private bool caloriesFieldSpecified;
    
    private decimal distanceAbsoluteField;
    
    private bool distanceAbsoluteFieldSpecified;
    
    private decimal distanceField;
    
    private bool distanceFieldSpecified;
    
    private decimal distanceDownhillField;
    
    private bool distanceDownhillFieldSpecified;
    
    private decimal distanceUphillField;
    
    private bool distanceUphillFieldSpecified;
    
    private decimal heartrateField;
    
    private bool heartrateFieldSpecified;
    
    private decimal inclineField;
    
    private bool inclineFieldSpecified;
    
    private decimal latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private decimal longitudeField;
    
    private bool longitudeFieldSpecified;
    
    private decimal powerField;
    
    private bool powerFieldSpecified;
    
    private decimal powerPerKGField;
    
    private bool powerPerKGFieldSpecified;
    
    private decimal riseRateField;
    
    private bool riseRateFieldSpecified;
    
    private decimal speedField;
    
    private bool speedFieldSpecified;
    
    private decimal speedTimeField;
    
    private bool speedTimeFieldSpecified;
    
    private decimal temperatureField;
    
    private bool temperatureFieldSpecified;
    
    private decimal trainingTimeField;
    
    private bool trainingTimeFieldSpecified;
    
    private decimal trainingTimeAbsoluteField;
    
    private bool trainingTimeAbsoluteFieldSpecified;
    
    private decimal trainingTimeDownhillField;
    
    private bool trainingTimeDownhillFieldSpecified;
    
    private decimal trainingTimeUphillField;
    
    private bool trainingTimeUphillFieldSpecified;
    
    private decimal workInKJField;
    
    private bool workInKJFieldSpecified;
    
    private decimal normalizedPowerField;
    
    private bool normalizedPowerFieldSpecified;
    
    private decimal rightBalanceField;
    
    private bool rightBalanceFieldSpecified;
    
    private decimal leftBalanceField;
    
    private bool leftBalanceFieldSpecified;
    
    private decimal timeBelowIntensityZonesField;
    
    private bool timeBelowIntensityZonesFieldSpecified;
    
    private decimal timeInIntensityZone1Field;
    
    private bool timeInIntensityZone1FieldSpecified;
    
    private decimal timeInIntensityZone2Field;
    
    private bool timeInIntensityZone2FieldSpecified;
    
    private decimal timeInIntensityZone3Field;
    
    private bool timeInIntensityZone3FieldSpecified;
    
    private decimal timeInIntensityZone4Field;
    
    private bool timeInIntensityZone4FieldSpecified;
    
    private decimal timeAboveIntensityZonesField;
    
    private bool timeAboveIntensityZonesFieldSpecified;
    
    private decimal timeInPowerZone1Field;
    
    private bool timeInPowerZone1FieldSpecified;
    
    private decimal timeInPowerZone2Field;
    
    private bool timeInPowerZone2FieldSpecified;
    
    private decimal timeInPowerZone3Field;
    
    private bool timeInPowerZone3FieldSpecified;
    
    private decimal timeInPowerZone4Field;
    
    private bool timeInPowerZone4FieldSpecified;
    
    private decimal timeInPowerZone5Field;
    
    private bool timeInPowerZone5FieldSpecified;
    
    private decimal timeInPowerZone6Field;
    
    private bool timeInPowerZone6FieldSpecified;
    
    private decimal timeInPowerZone7Field;
    
    private bool timeInPowerZone7FieldSpecified;
    
    private decimal pedalingTimeField;
    
    private bool pedalingTimeFieldSpecified;
    
    private decimal useForChartField;
    
    private bool useForChartFieldSpecified;
    
    private decimal useForTrackField;
    
    private bool useForTrackFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal altitude {
        get {
            return this.altitudeField;
        }
        set {
            this.altitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool altitudeSpecified {
        get {
            return this.altitudeFieldSpecified;
        }
        set {
            this.altitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal altitudeDifferencesDownhill {
        get {
            return this.altitudeDifferencesDownhillField;
        }
        set {
            this.altitudeDifferencesDownhillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool altitudeDifferencesDownhillSpecified {
        get {
            return this.altitudeDifferencesDownhillFieldSpecified;
        }
        set {
            this.altitudeDifferencesDownhillFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal altitudeDifferencesUphill {
        get {
            return this.altitudeDifferencesUphillField;
        }
        set {
            this.altitudeDifferencesUphillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool altitudeDifferencesUphillSpecified {
        get {
            return this.altitudeDifferencesUphillFieldSpecified;
        }
        set {
            this.altitudeDifferencesUphillFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal cadence {
        get {
            return this.cadenceField;
        }
        set {
            this.cadenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cadenceSpecified {
        get {
            return this.cadenceFieldSpecified;
        }
        set {
            this.cadenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal calories {
        get {
            return this.caloriesField;
        }
        set {
            this.caloriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool caloriesSpecified {
        get {
            return this.caloriesFieldSpecified;
        }
        set {
            this.caloriesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal distanceAbsolute {
        get {
            return this.distanceAbsoluteField;
        }
        set {
            this.distanceAbsoluteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool distanceAbsoluteSpecified {
        get {
            return this.distanceAbsoluteFieldSpecified;
        }
        set {
            this.distanceAbsoluteFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool distanceSpecified {
        get {
            return this.distanceFieldSpecified;
        }
        set {
            this.distanceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal distanceDownhill {
        get {
            return this.distanceDownhillField;
        }
        set {
            this.distanceDownhillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool distanceDownhillSpecified {
        get {
            return this.distanceDownhillFieldSpecified;
        }
        set {
            this.distanceDownhillFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal distanceUphill {
        get {
            return this.distanceUphillField;
        }
        set {
            this.distanceUphillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool distanceUphillSpecified {
        get {
            return this.distanceUphillFieldSpecified;
        }
        set {
            this.distanceUphillFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal heartrate {
        get {
            return this.heartrateField;
        }
        set {
            this.heartrateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool heartrateSpecified {
        get {
            return this.heartrateFieldSpecified;
        }
        set {
            this.heartrateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal incline {
        get {
            return this.inclineField;
        }
        set {
            this.inclineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool inclineSpecified {
        get {
            return this.inclineFieldSpecified;
        }
        set {
            this.inclineFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeSpecified {
        get {
            return this.latitudeFieldSpecified;
        }
        set {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeSpecified {
        get {
            return this.longitudeFieldSpecified;
        }
        set {
            this.longitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal power {
        get {
            return this.powerField;
        }
        set {
            this.powerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool powerSpecified {
        get {
            return this.powerFieldSpecified;
        }
        set {
            this.powerFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal powerPerKG {
        get {
            return this.powerPerKGField;
        }
        set {
            this.powerPerKGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool powerPerKGSpecified {
        get {
            return this.powerPerKGFieldSpecified;
        }
        set {
            this.powerPerKGFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal riseRate {
        get {
            return this.riseRateField;
        }
        set {
            this.riseRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool riseRateSpecified {
        get {
            return this.riseRateFieldSpecified;
        }
        set {
            this.riseRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool speedSpecified {
        get {
            return this.speedFieldSpecified;
        }
        set {
            this.speedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal speedTime {
        get {
            return this.speedTimeField;
        }
        set {
            this.speedTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool speedTimeSpecified {
        get {
            return this.speedTimeFieldSpecified;
        }
        set {
            this.speedTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal temperature {
        get {
            return this.temperatureField;
        }
        set {
            this.temperatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool temperatureSpecified {
        get {
            return this.temperatureFieldSpecified;
        }
        set {
            this.temperatureFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal trainingTime {
        get {
            return this.trainingTimeField;
        }
        set {
            this.trainingTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool trainingTimeSpecified {
        get {
            return this.trainingTimeFieldSpecified;
        }
        set {
            this.trainingTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal trainingTimeAbsolute {
        get {
            return this.trainingTimeAbsoluteField;
        }
        set {
            this.trainingTimeAbsoluteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool trainingTimeAbsoluteSpecified {
        get {
            return this.trainingTimeAbsoluteFieldSpecified;
        }
        set {
            this.trainingTimeAbsoluteFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal trainingTimeDownhill {
        get {
            return this.trainingTimeDownhillField;
        }
        set {
            this.trainingTimeDownhillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool trainingTimeDownhillSpecified {
        get {
            return this.trainingTimeDownhillFieldSpecified;
        }
        set {
            this.trainingTimeDownhillFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal trainingTimeUphill {
        get {
            return this.trainingTimeUphillField;
        }
        set {
            this.trainingTimeUphillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool trainingTimeUphillSpecified {
        get {
            return this.trainingTimeUphillFieldSpecified;
        }
        set {
            this.trainingTimeUphillFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal workInKJ {
        get {
            return this.workInKJField;
        }
        set {
            this.workInKJField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool workInKJSpecified {
        get {
            return this.workInKJFieldSpecified;
        }
        set {
            this.workInKJFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal normalizedPower {
        get {
            return this.normalizedPowerField;
        }
        set {
            this.normalizedPowerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool normalizedPowerSpecified {
        get {
            return this.normalizedPowerFieldSpecified;
        }
        set {
            this.normalizedPowerFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal rightBalance {
        get {
            return this.rightBalanceField;
        }
        set {
            this.rightBalanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rightBalanceSpecified {
        get {
            return this.rightBalanceFieldSpecified;
        }
        set {
            this.rightBalanceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal leftBalance {
        get {
            return this.leftBalanceField;
        }
        set {
            this.leftBalanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool leftBalanceSpecified {
        get {
            return this.leftBalanceFieldSpecified;
        }
        set {
            this.leftBalanceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal timeBelowIntensityZones {
        get {
            return this.timeBelowIntensityZonesField;
        }
        set {
            this.timeBelowIntensityZonesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeBelowIntensityZonesSpecified {
        get {
            return this.timeBelowIntensityZonesFieldSpecified;
        }
        set {
            this.timeBelowIntensityZonesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal timeInIntensityZone1 {
        get {
            return this.timeInIntensityZone1Field;
        }
        set {
            this.timeInIntensityZone1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeInIntensityZone1Specified {
        get {
            return this.timeInIntensityZone1FieldSpecified;
        }
        set {
            this.timeInIntensityZone1FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal timeInIntensityZone2 {
        get {
            return this.timeInIntensityZone2Field;
        }
        set {
            this.timeInIntensityZone2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeInIntensityZone2Specified {
        get {
            return this.timeInIntensityZone2FieldSpecified;
        }
        set {
            this.timeInIntensityZone2FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal timeInIntensityZone3 {
        get {
            return this.timeInIntensityZone3Field;
        }
        set {
            this.timeInIntensityZone3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeInIntensityZone3Specified {
        get {
            return this.timeInIntensityZone3FieldSpecified;
        }
        set {
            this.timeInIntensityZone3FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal timeInIntensityZone4 {
        get {
            return this.timeInIntensityZone4Field;
        }
        set {
            this.timeInIntensityZone4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeInIntensityZone4Specified {
        get {
            return this.timeInIntensityZone4FieldSpecified;
        }
        set {
            this.timeInIntensityZone4FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal timeAboveIntensityZones {
        get {
            return this.timeAboveIntensityZonesField;
        }
        set {
            this.timeAboveIntensityZonesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeAboveIntensityZonesSpecified {
        get {
            return this.timeAboveIntensityZonesFieldSpecified;
        }
        set {
            this.timeAboveIntensityZonesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal timeInPowerZone1 {
        get {
            return this.timeInPowerZone1Field;
        }
        set {
            this.timeInPowerZone1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeInPowerZone1Specified {
        get {
            return this.timeInPowerZone1FieldSpecified;
        }
        set {
            this.timeInPowerZone1FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal timeInPowerZone2 {
        get {
            return this.timeInPowerZone2Field;
        }
        set {
            this.timeInPowerZone2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeInPowerZone2Specified {
        get {
            return this.timeInPowerZone2FieldSpecified;
        }
        set {
            this.timeInPowerZone2FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal timeInPowerZone3 {
        get {
            return this.timeInPowerZone3Field;
        }
        set {
            this.timeInPowerZone3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeInPowerZone3Specified {
        get {
            return this.timeInPowerZone3FieldSpecified;
        }
        set {
            this.timeInPowerZone3FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal timeInPowerZone4 {
        get {
            return this.timeInPowerZone4Field;
        }
        set {
            this.timeInPowerZone4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeInPowerZone4Specified {
        get {
            return this.timeInPowerZone4FieldSpecified;
        }
        set {
            this.timeInPowerZone4FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal timeInPowerZone5 {
        get {
            return this.timeInPowerZone5Field;
        }
        set {
            this.timeInPowerZone5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeInPowerZone5Specified {
        get {
            return this.timeInPowerZone5FieldSpecified;
        }
        set {
            this.timeInPowerZone5FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal timeInPowerZone6 {
        get {
            return this.timeInPowerZone6Field;
        }
        set {
            this.timeInPowerZone6Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeInPowerZone6Specified {
        get {
            return this.timeInPowerZone6FieldSpecified;
        }
        set {
            this.timeInPowerZone6FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal timeInPowerZone7 {
        get {
            return this.timeInPowerZone7Field;
        }
        set {
            this.timeInPowerZone7Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeInPowerZone7Specified {
        get {
            return this.timeInPowerZone7FieldSpecified;
        }
        set {
            this.timeInPowerZone7FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal pedalingTime {
        get {
            return this.pedalingTimeField;
        }
        set {
            this.pedalingTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pedalingTimeSpecified {
        get {
            return this.pedalingTimeFieldSpecified;
        }
        set {
            this.pedalingTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal useForChart {
        get {
            return this.useForChartField;
        }
        set {
            this.useForChartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool useForChartSpecified {
        get {
            return this.useForChartFieldSpecified;
        }
        set {
            this.useForChartFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal useForTrack {
        get {
            return this.useForTrackField;
        }
        set {
            this.useForTrackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool useForTrackSpecified {
        get {
            return this.useForTrackFieldSpecified;
        }
        set {
            this.useForTrackFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ActivityMarker {
    
    private decimal caloriesField;
    
    private bool caloriesFieldSpecified;
    
    private string descriptionField;
    
    private decimal durationField;
    
    private bool durationFieldSpecified;
    
    private decimal numberField;
    
    private bool numberFieldSpecified;
    
    private decimal timeField;
    
    private bool timeFieldSpecified;
    
    private decimal timeAbsoluteField;
    
    private bool timeAbsoluteFieldSpecified;
    
    private string titleField;
    
    private string typeField;
    
    private decimal distanceField;
    
    private bool distanceFieldSpecified;
    
    private decimal distanceAbsoluteField;
    
    private bool distanceAbsoluteFieldSpecified;
    
    private decimal latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private decimal longitudeField;
    
    private bool longitudeFieldSpecified;
    
    private decimal altitudeDownhillField;
    
    private bool altitudeDownhillFieldSpecified;
    
    private decimal altitudeUphillField;
    
    private bool altitudeUphillFieldSpecified;
    
    private decimal averageAltitudeField;
    
    private bool averageAltitudeFieldSpecified;
    
    private decimal averageCadenceField;
    
    private bool averageCadenceFieldSpecified;
    
    private decimal averageHeartrateField;
    
    private bool averageHeartrateFieldSpecified;
    
    private decimal averageInclineDownhillField;
    
    private bool averageInclineDownhillFieldSpecified;
    
    private decimal averageInclineUphillField;
    
    private bool averageInclineUphillFieldSpecified;
    
    private decimal averagePowerField;
    
    private bool averagePowerFieldSpecified;
    
    private decimal averageSpeedField;
    
    private bool averageSpeedFieldSpecified;
    
    private decimal maximumAltitudeField;
    
    private bool maximumAltitudeFieldSpecified;
    
    private decimal maximumCadenceField;
    
    private bool maximumCadenceFieldSpecified;
    
    private decimal maximumHeartrateField;
    
    private bool maximumHeartrateFieldSpecified;
    
    private decimal maximumInclineDownhillField;
    
    private bool maximumInclineDownhillFieldSpecified;
    
    private decimal maximumInclineUphillField;
    
    private bool maximumInclineUphillFieldSpecified;
    
    private decimal maximumPowerField;
    
    private bool maximumPowerFieldSpecified;
    
    private decimal maximumSpeedField;
    
    private bool maximumSpeedFieldSpecified;
    
    private decimal minimumHeartrateField;
    
    private bool minimumHeartrateFieldSpecified;
    
    private decimal minimumSpeedField;
    
    private bool minimumSpeedFieldSpecified;
    
    private decimal normalizedPowerField;
    
    private bool normalizedPowerFieldSpecified;
    
    private decimal averageBalanceField;
    
    private bool averageBalanceFieldSpecified;
    
    private decimal pedalingTimeField;
    
    private bool pedalingTimeFieldSpecified;
    
    private decimal leftTorqueEffectivityField;
    
    private bool leftTorqueEffectivityFieldSpecified;
    
    private decimal rightTorqueEffectivityField;
    
    private bool rightTorqueEffectivityFieldSpecified;
    
    private decimal leftPedalingSmoothnessField;
    
    private bool leftPedalingSmoothnessFieldSpecified;
    
    private decimal rightPedalingSmoothnessField;
    
    private bool rightPedalingSmoothnessFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal calories {
        get {
            return this.caloriesField;
        }
        set {
            this.caloriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool caloriesSpecified {
        get {
            return this.caloriesFieldSpecified;
        }
        set {
            this.caloriesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool durationSpecified {
        get {
            return this.durationFieldSpecified;
        }
        set {
            this.durationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool numberSpecified {
        get {
            return this.numberFieldSpecified;
        }
        set {
            this.numberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeSpecified {
        get {
            return this.timeFieldSpecified;
        }
        set {
            this.timeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal timeAbsolute {
        get {
            return this.timeAbsoluteField;
        }
        set {
            this.timeAbsoluteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeAbsoluteSpecified {
        get {
            return this.timeAbsoluteFieldSpecified;
        }
        set {
            this.timeAbsoluteFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool distanceSpecified {
        get {
            return this.distanceFieldSpecified;
        }
        set {
            this.distanceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal distanceAbsolute {
        get {
            return this.distanceAbsoluteField;
        }
        set {
            this.distanceAbsoluteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool distanceAbsoluteSpecified {
        get {
            return this.distanceAbsoluteFieldSpecified;
        }
        set {
            this.distanceAbsoluteFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeSpecified {
        get {
            return this.latitudeFieldSpecified;
        }
        set {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeSpecified {
        get {
            return this.longitudeFieldSpecified;
        }
        set {
            this.longitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal altitudeDownhill {
        get {
            return this.altitudeDownhillField;
        }
        set {
            this.altitudeDownhillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool altitudeDownhillSpecified {
        get {
            return this.altitudeDownhillFieldSpecified;
        }
        set {
            this.altitudeDownhillFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal altitudeUphill {
        get {
            return this.altitudeUphillField;
        }
        set {
            this.altitudeUphillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool altitudeUphillSpecified {
        get {
            return this.altitudeUphillFieldSpecified;
        }
        set {
            this.altitudeUphillFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal averageAltitude {
        get {
            return this.averageAltitudeField;
        }
        set {
            this.averageAltitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool averageAltitudeSpecified {
        get {
            return this.averageAltitudeFieldSpecified;
        }
        set {
            this.averageAltitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal averageCadence {
        get {
            return this.averageCadenceField;
        }
        set {
            this.averageCadenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool averageCadenceSpecified {
        get {
            return this.averageCadenceFieldSpecified;
        }
        set {
            this.averageCadenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal averageHeartrate {
        get {
            return this.averageHeartrateField;
        }
        set {
            this.averageHeartrateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool averageHeartrateSpecified {
        get {
            return this.averageHeartrateFieldSpecified;
        }
        set {
            this.averageHeartrateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal averageInclineDownhill {
        get {
            return this.averageInclineDownhillField;
        }
        set {
            this.averageInclineDownhillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool averageInclineDownhillSpecified {
        get {
            return this.averageInclineDownhillFieldSpecified;
        }
        set {
            this.averageInclineDownhillFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal averageInclineUphill {
        get {
            return this.averageInclineUphillField;
        }
        set {
            this.averageInclineUphillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool averageInclineUphillSpecified {
        get {
            return this.averageInclineUphillFieldSpecified;
        }
        set {
            this.averageInclineUphillFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal averagePower {
        get {
            return this.averagePowerField;
        }
        set {
            this.averagePowerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool averagePowerSpecified {
        get {
            return this.averagePowerFieldSpecified;
        }
        set {
            this.averagePowerFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal averageSpeed {
        get {
            return this.averageSpeedField;
        }
        set {
            this.averageSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool averageSpeedSpecified {
        get {
            return this.averageSpeedFieldSpecified;
        }
        set {
            this.averageSpeedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maximumAltitude {
        get {
            return this.maximumAltitudeField;
        }
        set {
            this.maximumAltitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumAltitudeSpecified {
        get {
            return this.maximumAltitudeFieldSpecified;
        }
        set {
            this.maximumAltitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maximumCadence {
        get {
            return this.maximumCadenceField;
        }
        set {
            this.maximumCadenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumCadenceSpecified {
        get {
            return this.maximumCadenceFieldSpecified;
        }
        set {
            this.maximumCadenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maximumHeartrate {
        get {
            return this.maximumHeartrateField;
        }
        set {
            this.maximumHeartrateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumHeartrateSpecified {
        get {
            return this.maximumHeartrateFieldSpecified;
        }
        set {
            this.maximumHeartrateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maximumInclineDownhill {
        get {
            return this.maximumInclineDownhillField;
        }
        set {
            this.maximumInclineDownhillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumInclineDownhillSpecified {
        get {
            return this.maximumInclineDownhillFieldSpecified;
        }
        set {
            this.maximumInclineDownhillFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maximumInclineUphill {
        get {
            return this.maximumInclineUphillField;
        }
        set {
            this.maximumInclineUphillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumInclineUphillSpecified {
        get {
            return this.maximumInclineUphillFieldSpecified;
        }
        set {
            this.maximumInclineUphillFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maximumPower {
        get {
            return this.maximumPowerField;
        }
        set {
            this.maximumPowerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumPowerSpecified {
        get {
            return this.maximumPowerFieldSpecified;
        }
        set {
            this.maximumPowerFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maximumSpeed {
        get {
            return this.maximumSpeedField;
        }
        set {
            this.maximumSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumSpeedSpecified {
        get {
            return this.maximumSpeedFieldSpecified;
        }
        set {
            this.maximumSpeedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal minimumHeartrate {
        get {
            return this.minimumHeartrateField;
        }
        set {
            this.minimumHeartrateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minimumHeartrateSpecified {
        get {
            return this.minimumHeartrateFieldSpecified;
        }
        set {
            this.minimumHeartrateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal minimumSpeed {
        get {
            return this.minimumSpeedField;
        }
        set {
            this.minimumSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minimumSpeedSpecified {
        get {
            return this.minimumSpeedFieldSpecified;
        }
        set {
            this.minimumSpeedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal normalizedPower {
        get {
            return this.normalizedPowerField;
        }
        set {
            this.normalizedPowerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool normalizedPowerSpecified {
        get {
            return this.normalizedPowerFieldSpecified;
        }
        set {
            this.normalizedPowerFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal averageBalance {
        get {
            return this.averageBalanceField;
        }
        set {
            this.averageBalanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool averageBalanceSpecified {
        get {
            return this.averageBalanceFieldSpecified;
        }
        set {
            this.averageBalanceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal pedalingTime {
        get {
            return this.pedalingTimeField;
        }
        set {
            this.pedalingTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pedalingTimeSpecified {
        get {
            return this.pedalingTimeFieldSpecified;
        }
        set {
            this.pedalingTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal leftTorqueEffectivity {
        get {
            return this.leftTorqueEffectivityField;
        }
        set {
            this.leftTorqueEffectivityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool leftTorqueEffectivitySpecified {
        get {
            return this.leftTorqueEffectivityFieldSpecified;
        }
        set {
            this.leftTorqueEffectivityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal rightTorqueEffectivity {
        get {
            return this.rightTorqueEffectivityField;
        }
        set {
            this.rightTorqueEffectivityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rightTorqueEffectivitySpecified {
        get {
            return this.rightTorqueEffectivityFieldSpecified;
        }
        set {
            this.rightTorqueEffectivityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal leftPedalingSmoothness {
        get {
            return this.leftPedalingSmoothnessField;
        }
        set {
            this.leftPedalingSmoothnessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool leftPedalingSmoothnessSpecified {
        get {
            return this.leftPedalingSmoothnessFieldSpecified;
        }
        set {
            this.leftPedalingSmoothnessFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal rightPedalingSmoothness {
        get {
            return this.rightPedalingSmoothnessField;
        }
        set {
            this.rightPedalingSmoothnessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rightPedalingSmoothnessSpecified {
        get {
            return this.rightPedalingSmoothnessFieldSpecified;
        }
        set {
            this.rightPedalingSmoothnessFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
